# Generated by Django 2.0.5 on 2019-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=2000)),
                ('branch', models.CharField(max_length=2000)),
                ('mobno', models.IntegerField(default=0)),
            ],
        ),
    ]
